# Generated by Django 3.1.4 on 2022-07-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('rent_ammount', models.IntegerField(verbose_name='Cost')),
                ('room', models.IntegerField(verbose_name='Total Room')),
                ('address', models.TextField(default='', verbose_name='Address')),
                ('post', models.TextField(default='', verbose_name='Extra Informaion(Bed Room, Kitchen, Bathroom etc)')),
                ('mobile', models.CharField(default='', max_length=11, verbose_name='contact info')),
            ],
        ),
    ]
